### ISSUE TITLE
PLAGIARIZED CODE

### ISSUE THREAD

**Issue by genjutsu7** [AdityaSeth777/Shooting-Game#1]
Hi,

The code you posted on your repository has been copied from [this site](https://copyassignment.com/balloon-shooter-game-using-python-pygame). You have not credited the author of the post. Copyright infringement is a serious violation. 

Please take down this repository.

**Comment by AdityaSeth777** [comment]
Hello.

It's a serious thing to point blankly accuse anyone of plagiarism. This project was taught in a workshop in our college which I attended. Even if the codes do look similar, I absolutely have nothing to do with copying or plagiarism.
I actually spent my own time developing it. Maybe, someone else did before me and I appreciate them for it. I'm not calling this repo as my own unique creation but definitely, don't just point blankly accuse anyone of plagiarism.
Please at least know anything about me or my tech stack or tech background without coming up with this serious accusation. I think I made myself pretty clear.

If you have anything to discuss, I'd surely like to be emailed -> adityaseth.cse@gmail.com
